
R = /user/jhb/bin/R

# R = R

all:
	make init.Rout
#	make FewerWarnings.Rout
	make tests

init.Rout: init.R
	time ${R} --save < init.R   > init.Rout

Fuchs: Fuchs82-complex.Rout Fuchs82-components.Rout Fuchs82-is.Rout Fuchs82-order.Rout Fuchs82-paths.Rout Fuchs82-neighbours.Rout Fuchs82-shortest.Rout Fuchs82-is-separator.Rout Fuchs82-marginalize.Rout UterineCervix411.Rout

tests: Fuchs82.Rout Byssinosis38.Rout TestFiles.Rout TestSwitch.Rout TestSet.Rout TestDataFiles.Rout TestSubset.Rout TestDefault.Rout TestReturn.Rout TestSelection.Rout TestRedefine.Rout TestQtable.Rout TestTableValues.Rout TestModel.Rout TestModelList.Rout TestPrintModel.Rout TestIs.Rout TestTest.Rout TestEdit.Rout TestDrop.Rout TestStepwise.Rout TestEHInit.Rout TestEH.Rout TestToEH.Rout TestExtractEH.Rout TestForceEH.Rout TestAddDual.Rout TestCoCoModelObject.Rout TestKrippendorfObjects.Rout TestKrippendorfRecover.Rout

FewerWarnings.Rout: FewerWarnings.R
	make init.Rout
	time ${R} --save < FewerWarnings.R > FewerWarnings.Rout

UterineCervix411.Rout: UterineCervix411.r
	( echo "UterineCervix411.r      " ; \
	time ${R} --save < UterineCervix411.r     > UterineCervix411.Rout )

Fuchs82.Rout: Fuchs82.r
	( echo "Fuchs82.r               " ; \
	time ${R} --save < Fuchs82.r              > Fuchs82.Rout )

Fuchs82-is.Rout: Fuchs82-is.S
	( echo "Fuchs82-is.S            " ; \
	time ${R} --save < Fuchs82-is.S           > Fuchs82-is.Rout )

Fuchs82-order.Rout: Fuchs82-order.S
	( echo "Fuchs82-order.S         " ; \
	time ${R} --save < Fuchs82-order.S        > Fuchs82-order.Rout )

Fuchs82-paths.Rout: Fuchs82-paths.S
	( echo "Fuchs82-paths.S         " ; \
	time ${R} --save < Fuchs82-paths.S        > Fuchs82-paths.Rout )

Fuchs82-complex.Rout: Fuchs82-complex.S
	( echo "Fuchs82-complex.S       " ; \
	time ${R} --save < Fuchs82-complex.S      > Fuchs82-complex.Rout )

Fuchs82-components.Rout: Fuchs82-components.S
	( echo "Fuchs82-components.S    " ; \
	time ${R} --save < Fuchs82-components.S   > Fuchs82-components.Rout )

Fuchs82-neighbours.Rout: Fuchs82-neighbours.S
	( echo "Fuchs82-neighbours.S    " ; \
	time ${R} --save < Fuchs82-neighbours.S   > Fuchs82-neighbours.Rout )

Fuchs82-shortest.Rout: Fuchs82-shortest.S
	( echo "Fuchs82-shortest.S      " ; \
	time ${R} --save < Fuchs82-shortest.S     > Fuchs82-shortest.Rout )

Fuchs82-is-separator.Rout: Fuchs82-is-separator.S
	( echo "Fuchs82-is-separator.S  " ; \
	time ${R} --save < Fuchs82-is-separator.S > Fuchs82-is-separator.Rout )

Fuchs82-marginalize.Rout: Fuchs82-marginalize.S
	( echo "Fuchs82-marginalize.S  " ; \
	time ${R} --save < Fuchs82-marginalize.S > Fuchs82-marginalize.Rout )

Byssinosis38.Rout: Byssinosis38.r
	( echo "Byssinosis38.r          " ; \
	time ${R} --save < Byssinosis38.r         > Byssinosis38.Rout )

TestFiles.Rout: TestFiles.r
	( echo "TestFiles.S             " ; \
	time ${R} --no-save < TestFiles.r            > TestFiles.Rout )

TestSwitch.Rout: TestSwitch.r
	( echo "TestSwitch.S            " ; \
	time ${R} --no-save < TestSwitch.r           > TestSwitch.Rout )

TestSet.Rout: TestSet.r
	( echo "TestSet.S               " ; \
	time ${R} --no-save < TestSet.r              > TestSet.Rout )

TestDataFiles.Rout: TestDataFiles.r
	( echo "TestDataFiles.S         " ; \
	time ${R} --no-save < TestDataFiles.r        > TestDataFiles.Rout )

TestSubset.Rout: TestSubset.r
	( echo "TestSubset.S            " ; \
	time ${R} --no-save < TestSubset.r           > TestSubset.Rout )
	cp TestSubset.r TestSubset.S

TestDefault.Rout: TestDefault.r
	( echo "TestDefault.S           " ; \
	time ${R} --no-save < TestDefault.r          > TestDefault.Rout )

TestReturn.Rout: TestReturn.r
	( echo "TestReturn.S            " ; \
	time ${R} --no-save < TestReturn.r           > TestReturn.Rout )

TestSelection.Rout: TestSelection.r
	( echo "TestSelection.S         " ; \
	time ${R} --no-save < TestSelection.r        > TestSelection.Rout )

TestRedefine.Rout: TestRedefine.r
	( echo "TestRedefine.S          " ; \
	time ${R} --no-save < TestRedefine.r         > TestRedefine.Rout )

TestQtable.Rout: TestQtable.R
	( echo "TestQtable.S            " ; \
	time ${R} --no-save < TestQtable.R           > TestQtable.Rout )

TestTableValues.Rout: TestTableValues.r
	( echo "TestTableValues.S       " ; \
	time ${R} --no-save < TestTableValues.r      > TestTableValues.Rout )

TestModel.Rout: TestModel.r
	( echo "TestModel.S             " ; \
	time ${R} --no-save < TestModel.r            > TestModel.Rout )

TestModelList.Rout: TestModelList.r
	( echo "TestModelList.S         " ; \
	time ${R} --no-save < TestModelList.r        > TestModelList.Rout )

TestPrintModel.Rout: TestPrintModel.r
	( echo "TestPrintModel.S        " ; \
	time ${R} --no-save < TestPrintModel.r       > TestPrintModel.Rout )

TestIs.Rout: TestIs.r
	( echo "TestIs.S                " ; \
	time ${R} --no-save < TestIs.r               > TestIs.Rout )

TestTest.Rout: TestTest.r
	( echo "TestTest.S              " ; \
	time ${R} --no-save < TestTest.r             > TestTest.Rout )

TestEdit.Rout: TestEdit.r
	( echo "TestEdit.S              " ; \
	time ${R} --no-save < TestEdit.r             > TestEdit.Rout )

TestDrop.Rout: TestDrop.r
	( echo "TestDrop.S              " ; \
	time ${R} --no-save < TestDrop.r             > TestDrop.Rout )

TestStepwise.Rout: TestStepwise.r
	( echo "TestStepwise.S          " ; \
	time ${R} --no-save < TestStepwise.r         > TestStepwise.Rout )

TestEHInit.Rout: TestEHInit.r
	( echo "TestEHInit.S            " ; \
	time ${R} --no-save < TestEHInit.r           > TestEHInit.Rout )

TestEH.Rout: TestEH.r
	( echo "TestEH.S                " ; \
	time ${R} --no-save < TestEH.r               > TestEH.Rout )

TestToEH.Rout: TestToEH.r
	( echo "TestToEH.S              " ; \
	time ${R} --no-save < TestToEH.r             > TestToEH.Rout )

TestExtractEH.Rout: TestExtractEH.r
	( echo "TestExtractEH.S         " ; \
	time ${R} --no-save < TestExtractEH.r        > TestExtractEH.Rout )

TestForceEH.Rout: TestForceEH.r
	( echo "TestForceEH.S           " ; \
	time ${R} --no-save < TestForceEH.r          > TestForceEH.Rout )

TestAddDual.Rout: TestAddDual.r
	( echo "TestAddDual.S           " ; \
	time ${R} --no-save < TestAddDual.r          > TestAddDual.Rout )

TestCoCoModelObject.Rout: TestCoCoModelObject.r
	( echo "TestCoCoModelObject.S   " ; \
	time ${R} --no-save < TestCoCoModelObject.r   > TestCoCoModelObject.Rout ) 

TestKrippendorfObjects.Rout: TestKrippendorfObjects.r
	( echo "TestKrippendorfObjects.S           " ; \
	time ${R} --no-save < TestKrippendorfObjects.r > TestKrippendorfObjects.Rout )

TestKrippendorfRecover.Rout: TestKrippendorfRecover.r
	( echo "TestKrippendorfRecover.S           " ; \
	time ${R} --no-save < TestKrippendorfRecover.r > TestKrippendorfRecover.Rout )

subdir = R+S/tests/Test.R+CoCo

clean:
	@echo "cleaning in $(subdir)"
	@-rm -f *~

distclean: clean
	@-rm -rf Affald ? Work
