library(CoCo)
data(Byssinosis38    );Byssinosis38@.title	 ; returnTable(object = Byssinosis38    ); 
data(David79         );David79@.title		 ; returnTable(object = David79         ); 
data(Fever           );Fever@.title		 ; returnTable(object = Fever           ); 
data(Fuchs82         );Fuchs82@.title		 ; returnTable(object = Fuchs82         ); 
data(Hochberg        );Hochberg@.title		 ; returnTable(object = Hochberg        ); 
data(Reinis          );Reinis@.title		 ; returnTable(object = Reinis          ); 
data(Scrotal         );Scrotal@.title		 ; returnTable(object = Scrotal         ); 
data(UterineCervix411);UterineCervix411@.title   ; returnTable("sparse.table", object = UterineCervix411); 
quitCoCo()







