library(stats); # ;


  data(beavers);               # f("beavers",             "", beavers); 	# R		     
  data(UKLungDeaths);          # f("UKLungDeaths",        "", UKLungDeaths); 	# R		     
  data(discoveries);           f("discoveries",          "", discoveries); 	# R		   #   0   0   1   100     "discoveries"           
  data(Nile);                  f("Nile",                 "", Nile); 		# R		   #   0   0   1   100     "Nile"                  
  data(WWWusage);              f("WWWusage",             "", WWWusage); 	# R		   #   0   0   1   100     "WWWusage"              
  data(UKgas);                 f("UKgas",                "", UKgas); 		# R		   #   0   0   1   108     "UKgas"                 
  data(lynx);                  f("lynx",                 "", lynx); 		# R		   #   0   0   1   114     "lynx"                  
  data(presidents);            f("presidents",           "", presidents); 	# R		   #   0   0   1   120     "presidents"            
  data(AirPassengers);         f("AirPassengers",        "", AirPassengers); 	# R		   #   0   0   1   144     "AirPassengers"         
  data(BJsales);               f("BJsales",              "", BJsales); 		# R		   #   0   0   1   150     "BJsales"               
  data(Seatbelts);             f("Seatbelts",            "", Seatbelts); 	# R		   #   0   0   1   1536    "Seatbelts"             
  data(UKDriverDeaths);        f("UKDriverDeaths",       "", UKDriverDeaths); 	# R		   #   0   0   1   192     "UKDriverDeaths"        
  data(uspop);                 f("uspop",                "", uspop); 		# R		   #   0   0   1   19      "uspop"                 
  data(nottem);                f("nottem",               "", nottem); 		# R		   #   0   0   1   240     "nottem"                
  data(airmiles);              f("airmiles",             "", airmiles); 	# R		   #   0   0   1   24      "airmiles"              
  data(sunspots);              f("sunspots",             "", sunspots); 	# R		   #   0   0   1   2820    "sunspots"              
  data(sunspot);               f("sunspot",              "", sunspot); 		# R		   #   0   0   1   37      "sunspot"               
  data(ability.cov);           f("ability.cov",          "", ability.cov); 	# R		   #   0   0   1   3       "ability.cov"           
  data(Harman23.cor);          f("Harman23.cor",         "", Harman23.cor); 	# R		   #   0   0   1   3       "Harman23.cor"          
  data(Harman74.cor);          f("Harman74.cor",         "", Harman74.cor); 	# R		   #   0   0   1   3       "Harman74.cor"          
  data(co2);                   f("co2",                  "", co2); 		# R		   #   0   0   1   468     "co2"                   
  data(lh);                    f("lh",                   "", lh); 		# R		   #   0   0   1   48      "lh"                    
  data(nhtemp);                f("nhtemp",               "", nhtemp); 		# R		   #   0   0   1   60      "nhtemp"                
  data(UKLungDeaths);          f("fdeaths",              "", fdeaths);		# R		   #   0   0   1   72      "fdeaths"               
  data(UKLungDeaths);          f("ldeaths",              "", ldeaths);		# R		   #   0   0   1   72      "ldeaths"               
  data(UKLungDeaths);          f("mdeaths",              "", mdeaths);		# R		   #   0   0   1   72      "mdeaths"               
  data(USAccDeaths);           f("USAccDeaths",          "", USAccDeaths); 	# R		   #   0   0   1   72      "USAccDeaths"           
  data(EuStockMarkets);        f("EuStockMarkets",       "", EuStockMarkets); 	# R		   #   0   0   1   7440    "EuStockMarkets"        
  data(treering);              f("treering",             "", treering); 	# R		   #   0   0   1   7980    "treering"              
  data(JohnsonJohnson);        f("JohnsonJohnson",       "", JohnsonJohnson); 	# R		   #   0   0   1   84      "JohnsonJohnson"        
  data(austres);               f("austres",              "", austres); 		# R		   #   0   0   1   89      "austres"               
  data(LakeHuron);             f("LakeHuron",            "", LakeHuron); 	# R		   #   0   0   1   98      "LakeHuron"             
  data(BOD);                   f("BOD",                  "", BOD); 		# R		   #   2   0   2   6       "BOD"                   
  data(DNase);                 f("DNase",                "", DNase); 		# R		   #   3   1   2   176     "DNase"                 
  data(Puromycin);             f("Puromycin",            "", Puromycin); 	# R		   #   3   1   2   23      "Puromycin"             
  data(Orange);                f("Orange",               "", Orange); 		# R		   #   3   1   2   35      "Orange"                
  data(Indometh);              f("Indometh",             "", Indometh); 	# R		   #   3   1   2   66      "Indometh"              
  data(Loblolly);              f("Loblolly",             "", Loblolly); 	# R		   #   3   1   2   84      "Loblolly"              
  data(beavers);               f("beaver2",              "", beaver2); 		# R		   #   4   0   4   100     "beaver2"               
  data(beavers);               f("beaver1",              "", beaver1); 		# R		   #   4   0   4   114     "beaver1"               
  data(rock);                  f("rock",                 "", rock); 		# tab		   #   4   0   4   48      "rock"                  
  data(ChickWeight);           f("ChickWeight",          "", ChickWeight); 	# R		   #   4   2   2   578     "ChickWeight"           
  data(freeny);                f("freeny",               "", freeny); 		# R		   #   5   0   5   39      "freeny"                
  data(Theoph);                f("Theoph",               "", Theoph); 		# R		   #   5   1   4   132     "Theoph"                
  data(zCO2);                  f("CO2",                  "", CO2); 		# R		   #   5   3   2   84      "CO2"                   
