
### TestSwitch

  library(CoCo);
  ReinisCoCoObject <- Reinis()

# "status" ;                          status () ;
# "set.switch" ;                      set.switch () ;

  set.switch("timer"               , "flop")
  set.switch("timer"               , "what")
  set.switch("timer"               , "on")
  set.switch("timer"               , "what")
  set.switch("timer"               , "off")
  set.switch("timer"               , "what")
  set.switch("timer"               , "flop")
  set.switch("timer"               , "what")
  set.switch("timer"               , T)
  set.switch("timer"               , "what")
  set.switch("timer"               , F)
  set.switch("timer"               , "what")

  set.switch("partitioning"        , "what")
  set.switch("keyboard"            , "what")
  set.switch("echo"                , "what")
  set.switch("diary"               , "what")
  set.switch("timer"               , "what")
  set.switch("graph.mode"          , "what")
  set.switch("decomposable.mode"   , "what")
  set.switch("large"               , "what")
  set.switch("short.test.output"   , "what")
  set.switch("report"              , "what")
  set.switch("reuse.tests"         , "what")
  set.switch("adjusted.df"         , "what")
  set.switch("trace"               , "what")
  set.switch("exact.test"          , "what")
  set.switch("exact.only.log.l"    , "what")
  set.switch("fast"                , "what")
  set.switch("exact.test.total"    , "what")
  set.switch("exact.test.parts"    , "what")
  set.switch("exact.test.unparted" , "what")
  set.switch("graphical.search"    , "what")
  set.switch("note"                , "what")
  set.switch("debug"               , "what")
  set.switch("option"              , "what")
  set.switch("log"                 , "what")
  set.switch("dump"                , "what")
  set.switch("sorted"              , "what")
  set.switch("keep.diary"          , "what")
  set.switch("keep.report"         , "what")
  set.switch("keep.log"            , "what")
  set.switch("log.data"            , "what")
  set.switch("keep.dump"           , "what")
  set.switch("pausing.of.output"   , "what")
  set.switch("huge"                , "what")
  set.switch("ic"                  , "what")
  set.switch("bic"                 , "what")
  set.switch("em"                  , "what")
  set.switch("warnings"            , "what")

  status("all")
  status("formats")
  status("tests")
  status("exact")
  status("fix")
  status("ips")
  status("em")
  status("old")
  status("specification")
  status( "factors")
  status("observations")
  status("data")
  status("limits")
  status("files")
  status("other")
  status("search")
  status("eh")

  .quit()
