
(load "src/dialogmanager")
(load "src/dialoggraph")
(load "src/dialogbind")
(load "src/dialoghelp")
(load "src/dialogoptions")
(load "src/dialogdescription")
(load "src/dialogmodels")
(load "src/dialogblocks")
(load "src/dialogone")
(load "src/dialogvalues")
(load "src/dialogtest")
(load "src/dialogsearch")
(load "src/dialogeh")
