
sed -f NewName.sed   Old.r/Byssinosis38.r	     > Byssinosis38.S
sed -f NewName.sed   Old.r/component.r		     > component.S
sed -f NewName.sed   Old.r/components.r		     > components.S
sed -f NewName.sed   Old.r/Fuchs82.r		     > Fuchs82.S
sed -f NewName.sed   Old.r/TestAddDual.r	     > TestAddDual.S
sed -f NewName.sed   Old.r/TestCoCoModelObject.r     > TestCoCoModelObject.S
sed -f NewName.sed   Old.r/TestDataFiles.r	     > TestDataFiles.S
sed -f NewName.sed   Old.r/TestData.r		     > TestData.S
sed -f NewName.sed   Old.r/TestDefault.r	     > TestDefault.S
sed -f NewName.sed   Old.r/TestDrop.r		     > TestDrop.S
sed -f NewName.sed   Old.r/TestEdit.r		     > TestEdit.S
sed -f NewName.sed   Old.r/TestEHInit.r		     > TestEHInit.S
sed -f NewName.sed   Old.r/TestEH.r		     > TestEH.S
sed -f NewName.sed   Old.r/TestExtractEH.r	     > TestExtractEH.S
sed -f NewName.sed   Old.r/TestExtract.r	     > TestExtract.S
sed -f NewName.sed   Old.r/TestFiles.r		     > TestFiles.S
sed -f NewName.sed   Old.r/TestForceEH.r	     > TestForceEH.S
sed -f NewName.sed   Old.r/TestIs.r		     > TestIs.S
sed -f NewName.sed   Old.r/TestKrippendorfObjects.r  > TestKrippendorfObjects.S
sed -f NewName.sed   Old.r/TestKrippendorfRecover.r  > TestKrippendorfRecover.S
sed -f NewName.sed   Old.r/TestModelList.r	     > TestModelList.S
sed -f NewName.sed   Old.r/TestModel.r		     > TestModel.S
sed -f NewName.sed   Old.r/TestPrintModel.r	     > TestPrintModel.S
sed -f NewName.sed   Old.r/TestRedefine.r	     > TestRedefine.S
sed -f NewName.sed   Old.r/TestReturn.r		     > TestReturn.S
sed -f NewName.sed   Old.r/TestSelection.r	     > TestSelection.S
sed -f NewName.sed   Old.r/TestSet.r		     > TestSet.S
sed -f NewName.sed   Old.r/TestStepwise.r	     > TestStepwise.S
sed -f NewName.sed   Old.r/TestSubset.r		     > TestSubset.S
sed -f NewName.sed   Old.r/TestSwitch.r		     > TestSwitch.S
sed -f NewName.sed   Old.r/TestTableValues.r	     > TestTableValues.S
sed -f NewName.sed   Old.r/TestTest.r		     > TestTest.S
sed -f NewName.sed   Old.r/TestToEH.r		     > TestToEH.S
sed -f NewName.sed   Old.r/UterineCervix411.r	     > UterineCervix411.S
		     						     
sed -f NewName.sed   Old.S/Fuchs82-complex.S	     > Fuchs82-complex.S
sed -f NewName.sed   Old.S/Fuchs82-components.S	     > Fuchs82-components.S
sed -f NewName.sed   Old.S/Fuchs82-is.S		     > Fuchs82-is.S
sed -f NewName.sed   Old.S/Fuchs82-is-separator.S    > Fuchs82-is-separator.S
sed -f NewName.sed   Old.S/Fuchs82-marginalize.S     > Fuchs82-marginalize.S
sed -f NewName.sed   Old.S/Fuchs82-neighbours.S	     > Fuchs82-neighbours.S
sed -f NewName.sed   Old.S/Fuchs82-order.S	     > Fuchs82-order.S
sed -f NewName.sed   Old.S/Fuchs82-paths.S	     > Fuchs82-paths.S
sed -f NewName.sed   Old.S/Fuchs82-shortest.S	     > Fuchs82-shortest.S
sed -f NewName.sed   Old.S/Reinis.S		     > Reinis.S
sed -f NewName.sed   Old.S/TestSubset.S		     > TestSubset.S
		     						     
sed -f NewName.sed   Old.R/init.R		     > init.S
sed -f NewName.sed   Old.R/Reinis-data.R	     > Reinis-data.S
sed -f NewName.sed   Old.R/TestQtable.R              > TestQtable.S                 
