s/set\.switch/\.set\.switch/
s/coco.\id/object/
s/coco.\end/endCoCo/
s/___make\.\model/makeModel/
s/make\.\mips/makeMips/
s/make\.\coco/makeCoCo/
s/make\.current.\coco/makeCurrentCoCo/
s/current.\coco(/currentCoCo(/
s/current.\coco (/currentCoCo (/
s/\.quit/quitCoCo/
s/status (/showOptions(/g
s/status(/showOptions(/g
s/export/exportCoCo/
s/import\.coco/importCoCo/
s/set\.datastructure/\.set\.datastructure/g
s/set\.ordinal/setOrdinal/
s/exclude\.missing/excludeMissing/
s/em\.on/emOn/
s/set\.use\.variables/setUseVariables/g
s/enter\.names/enterNames/
s/enter\.data\.frame/enterDataFrame/
s/dimension/numberVariates/
s/return\.marginal\.dimension/returnNcells/
s/return\.specification/returnVariableDescription/
s/extract\.data/extractData/
s/enter\.table/enterTable/
s/enter\.list/enterList/
s/enter\.two\.lists/enterTwoLists/
s/\.enter\.double\.list/\.enter\.double\.list/
s/enter\.q\.table/enterQtable/
s/enter\.q\.list/enterQlist/
s/clean\.data/cleanData/
s/substitute\.data/randomTableReplacement/
s/printTable/showTable/
s/plotCoCo/.plotCoCo/
s/printContinuous/\.show\.continuous/
s/describe\.table/summaryTable/
s/return\.table/returnTable/
s/read\.model/enterModel/g
s/\.read\.n\.interactions/\.enter\.n\.interactions/
s/return\.model\.number/returnModelNumber/g
s/return\.model\.set/returnModelVariates/g
s/return\.model/returnModel/g
s/eh\.set\.base/ehSetBase/
s/base()/makeBase("current")/g
s/current()/makeCurrent("last")/g
s/base ()/makeBase("current")/g
s/current ()/makeCurrent("last")/g
s/_base/\.base/
s/_current/\.current/
s/make\.base/makeBase/g
s/make\.current/makeCurrent/g
s/printFormula/showFormula/
s/return\.complex/returnExpression/
s/return\.expression/returnExpression/
s/return\.junction\.tree/returnJunctionTree/
s/return\.components/returnSets/
s/printVertexOrder/showVertexOrder/
s/return\.vertex\.order/returnVertexOrder/
s/dispose\.of\.fitted\.values/\.dispose\.of\.fitted\.values/
s/printModel/showModel/
s/dispose\.of\.model/disposeOfModel/g
s/is\.model/propertyModel/
s/is\.submodel\.of/isSubmodel/g
s/is\.set/propertySet/
s/slice/partialAssociations/g
s/\.printCommonDecompositions/\.show\.common\.decompositions/
s/find\.log\.l/\.show\.log\.lik/g
s/find\.deviance/showDeviance/g
s/compute\.test/returnTest/g
s/return\.test/returnTest/g
s/return\.deviance/returnDeviance/
s/test(/showTest(/
s/test (/showTest (/
s/\.set\.showTest(/\.set\.test(/

s/\.set\.showTest (/\.set\.test (/
s/\.set\.exact\.showTest(/\.set\.exact\.test(/
s/\.set\.exact\.showTest (/\.set\.exact\.test (/
s/show\.tests/showTests/g
s/clean\.up/\.clean\.up/
s/dispose\.of\.q\.table/disposeOfQtable/
s/fix\.edges/\.fix\.edges/
s/return\.fix/returnFix/g
s/eh\.set\.main\.effects/ehSetMainEffects/
s/\.eh\.read\.base\.model/\.eh\.enter\.base\.model/
s/eh\.fix/ehForceFix/
s/dispose\.of\.eh/disposeOfEh/
s/eh\.extract/ehExtract/
s/eh\.find\.dual/ehFindDual/
s/eh\.add\.dual\.to\.class/ehForceAddDualToClass/
s/eh\.fit/ehFit/
s/eh\.accept/ehForceAccept/g
s/eh\.reject/ehForceReject/g
