library(nlme); # ;						                           	 		   

  data(Rail);                  f("Rail",                 "", Rail);				   #   2   1   1   18      "Rail"                  
  data(Relaxin);               f("Relaxin",              "", Relaxin);				   #   3   1   2   198     "Relaxin"               
  data(IGF);                   f("IGF",                  "", IGF);				   #   3   1   2   237     "IGF"                   
  data(Fatigue);               f("Fatigue",              "", Fatigue);				   #   3   1   2   262     "Fatigue"               
  data(Ovary);                 f("Ovary",                "", Ovary);				   #   3   1   2   308     "Ovary"                 
  data(Muscle);                f("Muscle",               "", Muscle);				   #   3   1   2   60      "Muscle"                
  data(Cefamandole);           f("Cefamandole",          "", Cefamandole);			   #   3   1   2   84      "Cefamandole"           
  data(ergoStool);             f("ergoStool",            "", ergoStool);			   #   3   2   1   36      "ergoStool"             
  data(Machines);              f("Machines",             "", Machines);				   #   3   2   1   54      "Machines"              
  data(Wheat);                 f("Wheat",                "", Wheat);				   #   4   1   3   48      "Wheat"                 
  data(Nitrendipene);          f("Nitrendipene",         "", Nitrendipene);			   #   4   1   3   89      "Nitrendipene"          
  data(Spruce);                f("Spruce",               "", Spruce);				   #   4   2   2   1027    "Spruce"                
  data(Pixel);                 f("Pixel",                "", Pixel);				   #   4   2   2   102     "Pixel"                 
  data(Orthodont);             f("Orthodont",            "", Orthodont);			   #   4   2   2   108     "Orthodont"             
# data(Milk);                  f("Milk",                 "", Milk);				   #   4   2   2   1337    "Milk"                  
  data(BodyWeight);            f("BodyWeight",           "", BodyWeight);			   #   4   2   2   176     "BodyWeight"            
  data(Glucose2);              f("Glucose2",             "", Glucose2);				   #   4   2   2   196     "Glucose2"              
# data(Oxboys);                f("Oxboys",               "", Oxboys);				   #   4   2   2   234     "Oxboys"                
  data(Glucose);               f("Glucose",              "", Glucose);				   #   4   2   2   378     "Glucose"               
# data(Wafer);                 # f("Wafer",              "", Wafer);				   #   4   2   2   400     "Wafer"                 
  data(Tetracycline1);         f("Tetracycline1",        "", Tetracycline1);			   #   4   2   2   40      "Tetracycline1"         
  data(Tetracycline2);         f("Tetracycline2",        "", Tetracycline2);			   #   4   2   2   40      "Tetracycline2"         
  data(Oats);                  f("Oats",                 "", Oats);				   #   4   2   2   72      "Oats"                  
  data(Meat);                  f("Meat",                 "", Meat);				   #   4   3   1   30      "Meat"                  
  data(Gun);                   f("Gun",                  "", Gun);				   #   4   3   1   36      "Gun"                   
  data(Assay);                 f("Assay",                "", Assay);				   #   4   3   1   60      "Assay"                 
  data(Alfalfa);               f("Alfalfa",              "", Alfalfa);				   #   4   3   1   72      "Alfalfa"               
  data(Dialyzer);              f("Dialyzer",             "", Dialyzer);				   #   5   2   3   140     "Dialyzer"              
  data(Earthquake);            f("Earthquake",           "", Earthquake);			   #   5   2   3   182     "Earthquake"            
# data(Wheat2);                f("Wheat2",               "", Wheat2);				   #   5   2   3   224     "Wheat2"                
# data(RatPupWeight);          f("RatPupWeight",         "", RatPupWeight);			   #   5   3   2   322     "RatPupWeight"          
  data(Soybean);               f("Soybean",              "", Soybean);				   #   5   3   2   412     "Soybean"               
  data(PBG);                   f("PBG",                  "", PBG);				   #   5   3   2   60      "PBG"                   
  data(Oxide);                 f("Oxide",                "", Oxide);				   #   5   4   1   72      "Oxide"                 
  data(Gasoline);              f("Gasoline",             "", Gasoline);				   #   6   1   5   32      "Gasoline"              
  data(MathAchieve);           f("MathAchieve",          "", MathAchieve[,-1]);			   #   6   3   3   7185    "MathAchieve"           
# data(MathAchSchool);         f("MathAchSchool",        "", MathAchSchool);			   #   7   3   4   160     "MathAchSchool"         

  data(Phenobarb);             f("Phenobarb",            "", Phenobarb[,-1]);			   #   7   3   4   744     "Phenobarb"             
  data(Remifentanil);          f("Remifentanil",         "", Remifentanil[,-c(1,2)]);		   #   12  2   10  2107    "Remifentanil"          
  data(Quinidine);             f("Quinidine",            "", Quinidine[,-1]);			   #   14  6   8   1471    "Quinidine"             
  data(bdf);                   f("bdf",                  "", bdf[,-c(1,2)]);			   #   28  8   20  2287    "bdf"                   

# data(Phenobarb);             f("Phenobarb",            "", Phenobarb);			   #   7   3   4   744     "Phenobarb"             
# data(Remifentanil);          f("Remifentanil",         "", Remifentanil);			   #   12  2   10  2107    "Remifentanil"          
# data(Quinidine);             f("Quinidine",            "", Quinidine);			   #   14  6   8   1471    "Quinidine"             
# data(bdf);                   f("bdf",                  "", bdf);				   #   28  8   20  2287    "bdf"                   
